/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EnglishRouteImport } from './routes/english'
import { Route as DevlabRouteImport } from './routes/devlab'
import { Route as BitacoraRouteImport } from './routes/bitacora'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishRoute = EnglishRouteImport.update({
  id: '/english',
  path: '/english',
  getParentRoute: () => rootRouteImport,
} as any)
const DevlabRoute = DevlabRouteImport.update({
  id: '/devlab',
  path: '/devlab',
  getParentRoute: () => rootRouteImport,
} as any)
const BitacoraRoute = BitacoraRouteImport.update({
  id: '/bitacora',
  path: '/bitacora',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bitacora': typeof BitacoraRoute
  '/devlab': typeof DevlabRoute
  '/english': typeof EnglishRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bitacora': typeof BitacoraRoute
  '/devlab': typeof DevlabRoute
  '/english': typeof EnglishRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bitacora': typeof BitacoraRoute
  '/devlab': typeof DevlabRoute
  '/english': typeof EnglishRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bitacora'
    | '/devlab'
    | '/english'
    | '/login'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bitacora' | '/devlab' | '/english' | '/login' | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/bitacora'
    | '/devlab'
    | '/english'
    | '/login'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BitacoraRoute: typeof BitacoraRoute
  DevlabRoute: typeof DevlabRoute
  EnglishRoute: typeof EnglishRoute
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english': {
      id: '/english'
      path: '/english'
      fullPath: '/english'
      preLoaderRoute: typeof EnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devlab': {
      id: '/devlab'
      path: '/devlab'
      fullPath: '/devlab'
      preLoaderRoute: typeof DevlabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitacora': {
      id: '/bitacora'
      path: '/bitacora'
      fullPath: '/bitacora'
      preLoaderRoute: typeof BitacoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BitacoraRoute: BitacoraRoute,
  DevlabRoute: DevlabRoute,
  EnglishRoute: EnglishRoute,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
