/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EnglishRouteImport } from './routes/english'
import { Route as DevlabRouteImport } from './routes/devlab'
import { Route as BitacoraRouteImport } from './routes/bitacora'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as FacultyIndexRouteImport } from './routes/faculty/index'
import { Route as EnglishIndexRouteImport } from './routes/english/index'
import { Route as FacultySubjectIdRouteImport } from './routes/faculty/$subjectId'
import { Route as EnglishVocabRouteImport } from './routes/english/vocab'
import { Route as EnglishShadowingRouteImport } from './routes/english/shadowing'
import { Route as EnglishEvaluatorRouteImport } from './routes/english/evaluator'
import { Route as EnglishBooksRouteImport } from './routes/english/books'
import { Route as EnglishAnkiRouteImport } from './routes/english/anki'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishRoute = EnglishRouteImport.update({
  id: '/english',
  path: '/english',
  getParentRoute: () => rootRouteImport,
} as any)
const DevlabRoute = DevlabRouteImport.update({
  id: '/devlab',
  path: '/devlab',
  getParentRoute: () => rootRouteImport,
} as any)
const BitacoraRoute = BitacoraRouteImport.update({
  id: '/bitacora',
  path: '/bitacora',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyIndexRoute = FacultyIndexRouteImport.update({
  id: '/faculty/',
  path: '/faculty/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishIndexRoute = EnglishIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnglishRoute,
} as any)
const FacultySubjectIdRoute = FacultySubjectIdRouteImport.update({
  id: '/faculty/$subjectId',
  path: '/faculty/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishVocabRoute = EnglishVocabRouteImport.update({
  id: '/vocab',
  path: '/vocab',
  getParentRoute: () => EnglishRoute,
} as any)
const EnglishShadowingRoute = EnglishShadowingRouteImport.update({
  id: '/shadowing',
  path: '/shadowing',
  getParentRoute: () => EnglishRoute,
} as any)
const EnglishEvaluatorRoute = EnglishEvaluatorRouteImport.update({
  id: '/evaluator',
  path: '/evaluator',
  getParentRoute: () => EnglishRoute,
} as any)
const EnglishBooksRoute = EnglishBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => EnglishRoute,
} as any)
const EnglishAnkiRoute = EnglishAnkiRouteImport.update({
  id: '/anki',
  path: '/anki',
  getParentRoute: () => EnglishRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bitacora': typeof BitacoraRoute
  '/devlab': typeof DevlabRoute
  '/english': typeof EnglishRouteWithChildren
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/english/anki': typeof EnglishAnkiRoute
  '/english/books': typeof EnglishBooksRoute
  '/english/evaluator': typeof EnglishEvaluatorRoute
  '/english/shadowing': typeof EnglishShadowingRoute
  '/english/vocab': typeof EnglishVocabRoute
  '/faculty/$subjectId': typeof FacultySubjectIdRoute
  '/english/': typeof EnglishIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/library/': typeof LibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bitacora': typeof BitacoraRoute
  '/devlab': typeof DevlabRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/english/anki': typeof EnglishAnkiRoute
  '/english/books': typeof EnglishBooksRoute
  '/english/evaluator': typeof EnglishEvaluatorRoute
  '/english/shadowing': typeof EnglishShadowingRoute
  '/english/vocab': typeof EnglishVocabRoute
  '/faculty/$subjectId': typeof FacultySubjectIdRoute
  '/english': typeof EnglishIndexRoute
  '/faculty': typeof FacultyIndexRoute
  '/library': typeof LibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bitacora': typeof BitacoraRoute
  '/devlab': typeof DevlabRoute
  '/english': typeof EnglishRouteWithChildren
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/english/anki': typeof EnglishAnkiRoute
  '/english/books': typeof EnglishBooksRoute
  '/english/evaluator': typeof EnglishEvaluatorRoute
  '/english/shadowing': typeof EnglishShadowingRoute
  '/english/vocab': typeof EnglishVocabRoute
  '/faculty/$subjectId': typeof FacultySubjectIdRoute
  '/english/': typeof EnglishIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/library/': typeof LibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bitacora'
    | '/devlab'
    | '/english'
    | '/login'
    | '/auth/callback'
    | '/english/anki'
    | '/english/books'
    | '/english/evaluator'
    | '/english/shadowing'
    | '/english/vocab'
    | '/faculty/$subjectId'
    | '/english/'
    | '/faculty/'
    | '/library/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bitacora'
    | '/devlab'
    | '/login'
    | '/auth/callback'
    | '/english/anki'
    | '/english/books'
    | '/english/evaluator'
    | '/english/shadowing'
    | '/english/vocab'
    | '/faculty/$subjectId'
    | '/english'
    | '/faculty'
    | '/library'
  id:
    | '__root__'
    | '/'
    | '/bitacora'
    | '/devlab'
    | '/english'
    | '/login'
    | '/auth/callback'
    | '/english/anki'
    | '/english/books'
    | '/english/evaluator'
    | '/english/shadowing'
    | '/english/vocab'
    | '/faculty/$subjectId'
    | '/english/'
    | '/faculty/'
    | '/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BitacoraRoute: typeof BitacoraRoute
  DevlabRoute: typeof DevlabRoute
  EnglishRoute: typeof EnglishRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  FacultySubjectIdRoute: typeof FacultySubjectIdRoute
  FacultyIndexRoute: typeof FacultyIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english': {
      id: '/english'
      path: '/english'
      fullPath: '/english'
      preLoaderRoute: typeof EnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devlab': {
      id: '/devlab'
      path: '/devlab'
      fullPath: '/devlab'
      preLoaderRoute: typeof DevlabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitacora': {
      id: '/bitacora'
      path: '/bitacora'
      fullPath: '/bitacora'
      preLoaderRoute: typeof BitacoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/': {
      id: '/faculty/'
      path: '/faculty'
      fullPath: '/faculty/'
      preLoaderRoute: typeof FacultyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english/': {
      id: '/english/'
      path: '/'
      fullPath: '/english/'
      preLoaderRoute: typeof EnglishIndexRouteImport
      parentRoute: typeof EnglishRoute
    }
    '/faculty/$subjectId': {
      id: '/faculty/$subjectId'
      path: '/faculty/$subjectId'
      fullPath: '/faculty/$subjectId'
      preLoaderRoute: typeof FacultySubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english/vocab': {
      id: '/english/vocab'
      path: '/vocab'
      fullPath: '/english/vocab'
      preLoaderRoute: typeof EnglishVocabRouteImport
      parentRoute: typeof EnglishRoute
    }
    '/english/shadowing': {
      id: '/english/shadowing'
      path: '/shadowing'
      fullPath: '/english/shadowing'
      preLoaderRoute: typeof EnglishShadowingRouteImport
      parentRoute: typeof EnglishRoute
    }
    '/english/evaluator': {
      id: '/english/evaluator'
      path: '/evaluator'
      fullPath: '/english/evaluator'
      preLoaderRoute: typeof EnglishEvaluatorRouteImport
      parentRoute: typeof EnglishRoute
    }
    '/english/books': {
      id: '/english/books'
      path: '/books'
      fullPath: '/english/books'
      preLoaderRoute: typeof EnglishBooksRouteImport
      parentRoute: typeof EnglishRoute
    }
    '/english/anki': {
      id: '/english/anki'
      path: '/anki'
      fullPath: '/english/anki'
      preLoaderRoute: typeof EnglishAnkiRouteImport
      parentRoute: typeof EnglishRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EnglishRouteChildren {
  EnglishAnkiRoute: typeof EnglishAnkiRoute
  EnglishBooksRoute: typeof EnglishBooksRoute
  EnglishEvaluatorRoute: typeof EnglishEvaluatorRoute
  EnglishShadowingRoute: typeof EnglishShadowingRoute
  EnglishVocabRoute: typeof EnglishVocabRoute
  EnglishIndexRoute: typeof EnglishIndexRoute
}

const EnglishRouteChildren: EnglishRouteChildren = {
  EnglishAnkiRoute: EnglishAnkiRoute,
  EnglishBooksRoute: EnglishBooksRoute,
  EnglishEvaluatorRoute: EnglishEvaluatorRoute,
  EnglishShadowingRoute: EnglishShadowingRoute,
  EnglishVocabRoute: EnglishVocabRoute,
  EnglishIndexRoute: EnglishIndexRoute,
}

const EnglishRouteWithChildren =
  EnglishRoute._addFileChildren(EnglishRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BitacoraRoute: BitacoraRoute,
  DevlabRoute: DevlabRoute,
  EnglishRoute: EnglishRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  FacultySubjectIdRoute: FacultySubjectIdRoute,
  FacultyIndexRoute: FacultyIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
