/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EnglishRouteImport } from './routes/english'
import { Route as DevlabRouteImport } from './routes/devlab'
import { Route as BitacoraRouteImport } from './routes/bitacora'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyIndexRouteImport } from './routes/study/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as FacultyIndexRouteImport } from './routes/faculty/index'
import { Route as EnglishIndexRouteImport } from './routes/english/index'
import { Route as StudyDecksRouteImport } from './routes/study/decks'
import { Route as FacultySubjectIdRouteImport } from './routes/faculty/$subjectId'
import { Route as EnglishVocabRouteImport } from './routes/english/vocab'
import { Route as EnglishShadowingRouteImport } from './routes/english/shadowing'
import { Route as EnglishEvaluatorRouteImport } from './routes/english/evaluator'
import { Route as EnglishDailyRouteImport } from './routes/english/daily'
import { Route as EnglishBooksRouteImport } from './routes/english/books'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as StudyQuizzesIndexRouteImport } from './routes/study/quizzes/index'
import { Route as StudyQuizzesQuizIdRouteImport } from './routes/study/quizzes/$quizId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishRoute = EnglishRouteImport.update({
  id: '/english',
  path: '/english',
  getParentRoute: () => rootRouteImport,
} as any)
const DevlabRoute = DevlabRouteImport.update({
  id: '/devlab',
  path: '/devlab',
  getParentRoute: () => rootRouteImport,
} as any)
const BitacoraRoute = BitacoraRouteImport.update({
  id: '/bitacora',
  path: '/bitacora',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIndexRoute = StudyIndexRouteImport.update({
  id: '/study/',
  path: '/study/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyIndexRoute = FacultyIndexRouteImport.update({
  id: '/faculty/',
  path: '/faculty/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishIndexRoute = EnglishIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnglishRoute,
} as any)
const StudyDecksRoute = StudyDecksRouteImport.update({
  id: '/study/decks',
  path: '/study/decks',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultySubjectIdRoute = FacultySubjectIdRouteImport.update({
  id: '/faculty/$subjectId',
  path: '/faculty/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishVocabRoute = EnglishVocabRouteImport.update({
  id: '/vocab',
  path: '/vocab',
  getParentRoute: () => EnglishRoute,
} as any)
const EnglishShadowingRoute = EnglishShadowingRouteImport.update({
  id: '/shadowing',
  path: '/shadowing',
  getParentRoute: () => EnglishRoute,
} as any)
const EnglishEvaluatorRoute = EnglishEvaluatorRouteImport.update({
  id: '/evaluator',
  path: '/evaluator',
  getParentRoute: () => EnglishRoute,
} as any)
const EnglishDailyRoute = EnglishDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => EnglishRoute,
} as any)
const EnglishBooksRoute = EnglishBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => EnglishRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyQuizzesIndexRoute = StudyQuizzesIndexRouteImport.update({
  id: '/study/quizzes/',
  path: '/study/quizzes/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyQuizzesQuizIdRoute = StudyQuizzesQuizIdRouteImport.update({
  id: '/study/quizzes/$quizId',
  path: '/study/quizzes/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bitacora': typeof BitacoraRoute
  '/devlab': typeof DevlabRoute
  '/english': typeof EnglishRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/english/books': typeof EnglishBooksRoute
  '/english/daily': typeof EnglishDailyRoute
  '/english/evaluator': typeof EnglishEvaluatorRoute
  '/english/shadowing': typeof EnglishShadowingRoute
  '/english/vocab': typeof EnglishVocabRoute
  '/faculty/$subjectId': typeof FacultySubjectIdRoute
  '/study/decks': typeof StudyDecksRoute
  '/english/': typeof EnglishIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/study/': typeof StudyIndexRoute
  '/study/quizzes/$quizId': typeof StudyQuizzesQuizIdRoute
  '/study/quizzes/': typeof StudyQuizzesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bitacora': typeof BitacoraRoute
  '/devlab': typeof DevlabRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/english/books': typeof EnglishBooksRoute
  '/english/daily': typeof EnglishDailyRoute
  '/english/evaluator': typeof EnglishEvaluatorRoute
  '/english/shadowing': typeof EnglishShadowingRoute
  '/english/vocab': typeof EnglishVocabRoute
  '/faculty/$subjectId': typeof FacultySubjectIdRoute
  '/study/decks': typeof StudyDecksRoute
  '/english': typeof EnglishIndexRoute
  '/faculty': typeof FacultyIndexRoute
  '/library': typeof LibraryIndexRoute
  '/study': typeof StudyIndexRoute
  '/study/quizzes/$quizId': typeof StudyQuizzesQuizIdRoute
  '/study/quizzes': typeof StudyQuizzesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bitacora': typeof BitacoraRoute
  '/devlab': typeof DevlabRoute
  '/english': typeof EnglishRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/english/books': typeof EnglishBooksRoute
  '/english/daily': typeof EnglishDailyRoute
  '/english/evaluator': typeof EnglishEvaluatorRoute
  '/english/shadowing': typeof EnglishShadowingRoute
  '/english/vocab': typeof EnglishVocabRoute
  '/faculty/$subjectId': typeof FacultySubjectIdRoute
  '/study/decks': typeof StudyDecksRoute
  '/english/': typeof EnglishIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/study/': typeof StudyIndexRoute
  '/study/quizzes/$quizId': typeof StudyQuizzesQuizIdRoute
  '/study/quizzes/': typeof StudyQuizzesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bitacora'
    | '/devlab'
    | '/english'
    | '/login'
    | '/profile'
    | '/auth/callback'
    | '/english/books'
    | '/english/daily'
    | '/english/evaluator'
    | '/english/shadowing'
    | '/english/vocab'
    | '/faculty/$subjectId'
    | '/study/decks'
    | '/english/'
    | '/faculty/'
    | '/library/'
    | '/study/'
    | '/study/quizzes/$quizId'
    | '/study/quizzes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bitacora'
    | '/devlab'
    | '/login'
    | '/profile'
    | '/auth/callback'
    | '/english/books'
    | '/english/daily'
    | '/english/evaluator'
    | '/english/shadowing'
    | '/english/vocab'
    | '/faculty/$subjectId'
    | '/study/decks'
    | '/english'
    | '/faculty'
    | '/library'
    | '/study'
    | '/study/quizzes/$quizId'
    | '/study/quizzes'
  id:
    | '__root__'
    | '/'
    | '/bitacora'
    | '/devlab'
    | '/english'
    | '/login'
    | '/profile'
    | '/auth/callback'
    | '/english/books'
    | '/english/daily'
    | '/english/evaluator'
    | '/english/shadowing'
    | '/english/vocab'
    | '/faculty/$subjectId'
    | '/study/decks'
    | '/english/'
    | '/faculty/'
    | '/library/'
    | '/study/'
    | '/study/quizzes/$quizId'
    | '/study/quizzes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BitacoraRoute: typeof BitacoraRoute
  DevlabRoute: typeof DevlabRoute
  EnglishRoute: typeof EnglishRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  FacultySubjectIdRoute: typeof FacultySubjectIdRoute
  StudyDecksRoute: typeof StudyDecksRoute
  FacultyIndexRoute: typeof FacultyIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  StudyIndexRoute: typeof StudyIndexRoute
  StudyQuizzesQuizIdRoute: typeof StudyQuizzesQuizIdRoute
  StudyQuizzesIndexRoute: typeof StudyQuizzesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english': {
      id: '/english'
      path: '/english'
      fullPath: '/english'
      preLoaderRoute: typeof EnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devlab': {
      id: '/devlab'
      path: '/devlab'
      fullPath: '/devlab'
      preLoaderRoute: typeof DevlabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitacora': {
      id: '/bitacora'
      path: '/bitacora'
      fullPath: '/bitacora'
      preLoaderRoute: typeof BitacoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/': {
      id: '/study/'
      path: '/study'
      fullPath: '/study/'
      preLoaderRoute: typeof StudyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/': {
      id: '/faculty/'
      path: '/faculty'
      fullPath: '/faculty/'
      preLoaderRoute: typeof FacultyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english/': {
      id: '/english/'
      path: '/'
      fullPath: '/english/'
      preLoaderRoute: typeof EnglishIndexRouteImport
      parentRoute: typeof EnglishRoute
    }
    '/study/decks': {
      id: '/study/decks'
      path: '/study/decks'
      fullPath: '/study/decks'
      preLoaderRoute: typeof StudyDecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/$subjectId': {
      id: '/faculty/$subjectId'
      path: '/faculty/$subjectId'
      fullPath: '/faculty/$subjectId'
      preLoaderRoute: typeof FacultySubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english/vocab': {
      id: '/english/vocab'
      path: '/vocab'
      fullPath: '/english/vocab'
      preLoaderRoute: typeof EnglishVocabRouteImport
      parentRoute: typeof EnglishRoute
    }
    '/english/shadowing': {
      id: '/english/shadowing'
      path: '/shadowing'
      fullPath: '/english/shadowing'
      preLoaderRoute: typeof EnglishShadowingRouteImport
      parentRoute: typeof EnglishRoute
    }
    '/english/evaluator': {
      id: '/english/evaluator'
      path: '/evaluator'
      fullPath: '/english/evaluator'
      preLoaderRoute: typeof EnglishEvaluatorRouteImport
      parentRoute: typeof EnglishRoute
    }
    '/english/daily': {
      id: '/english/daily'
      path: '/daily'
      fullPath: '/english/daily'
      preLoaderRoute: typeof EnglishDailyRouteImport
      parentRoute: typeof EnglishRoute
    }
    '/english/books': {
      id: '/english/books'
      path: '/books'
      fullPath: '/english/books'
      preLoaderRoute: typeof EnglishBooksRouteImport
      parentRoute: typeof EnglishRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/quizzes/': {
      id: '/study/quizzes/'
      path: '/study/quizzes'
      fullPath: '/study/quizzes/'
      preLoaderRoute: typeof StudyQuizzesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/quizzes/$quizId': {
      id: '/study/quizzes/$quizId'
      path: '/study/quizzes/$quizId'
      fullPath: '/study/quizzes/$quizId'
      preLoaderRoute: typeof StudyQuizzesQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EnglishRouteChildren {
  EnglishBooksRoute: typeof EnglishBooksRoute
  EnglishDailyRoute: typeof EnglishDailyRoute
  EnglishEvaluatorRoute: typeof EnglishEvaluatorRoute
  EnglishShadowingRoute: typeof EnglishShadowingRoute
  EnglishVocabRoute: typeof EnglishVocabRoute
  EnglishIndexRoute: typeof EnglishIndexRoute
}

const EnglishRouteChildren: EnglishRouteChildren = {
  EnglishBooksRoute: EnglishBooksRoute,
  EnglishDailyRoute: EnglishDailyRoute,
  EnglishEvaluatorRoute: EnglishEvaluatorRoute,
  EnglishShadowingRoute: EnglishShadowingRoute,
  EnglishVocabRoute: EnglishVocabRoute,
  EnglishIndexRoute: EnglishIndexRoute,
}

const EnglishRouteWithChildren =
  EnglishRoute._addFileChildren(EnglishRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BitacoraRoute: BitacoraRoute,
  DevlabRoute: DevlabRoute,
  EnglishRoute: EnglishRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  FacultySubjectIdRoute: FacultySubjectIdRoute,
  StudyDecksRoute: StudyDecksRoute,
  FacultyIndexRoute: FacultyIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  StudyIndexRoute: StudyIndexRoute,
  StudyQuizzesQuizIdRoute: StudyQuizzesQuizIdRoute,
  StudyQuizzesIndexRoute: StudyQuizzesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
